### ISSUE TITLE
Πρόβλεψη αποθήκευσης πληροφορίας στη βάση που αφορά ...

### ISSUE THREAD

**Issue by jhaniot** [pdecrete/rektis-applications-front#36]
... στην Πράξη με την οποία προσλαμβάνεται ο εκπαιδευτικός.
Υπάρχουν διάφορα λογότυπα που μπορούν να μπουν στην αίτηση ανάλογα με την Πράξη με την οποία προσλαμβάνεται ο εκπαιδευτικός.

**Comment by spapad** [comment]
Η λειτουργία θα αφορά το backend
